definitions:
  ChangePinRequest:
    properties:
      new_pin:
        type: string
    type: object
  ChangePinResponse:
    properties:
      message:
        type: string
    type: object
  TriggerFingerprintModeResponse:
    properties:
      message:
        type: string
    type: object
  TriggerOpenDoorResponse:
    properties:
      message:
        type: string
    type: object
  TriggerRFIDModeResponse:
    properties:
      message:
        type: string
    type: object
  ValidatePinRequest:
    properties:
      pin:
        type: string
    type: object
  ValidatePinResponse:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  title: API Smart Door Lock IoT
  version: "1.0"
paths:
  /api/v1/configuration/pin:
    post:
      operationId: ValidatePin
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ValidatePinRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ValidatePinResponse'
      tags:
      - Configuration
    put:
      operationId: ChangePin
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/ChangePinRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ChangePinResponse'
      tags:
      - Configuration
  /api/v1/control/fingerprint-mode:
    post:
      operationId: TriggerFingerprintMode
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TriggerFingerprintModeResponse'
      tags:
      - Control
  /api/v1/control/open-door:
    post:
      operationId: TriggerOpenDoor
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TriggerOpenDoorResponse'
      tags:
      - Control
  /api/v1/control/rfid-mode:
    post:
      operationId: TriggerRFIDMode
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TriggerRFIDModeResponse'
      tags:
      - Control
swagger: "2.0"
